version: 2.1
orbs:
   codecov: codecov/codecov@1.0.4
jobs:
   build:
      working_directory: ~/Spartez
      docker:
         - image: circleci/openjdk:8-jdk-browsers
      steps:
         - checkout
         - restore_cache:
            key: Spartez-{{ checksum "pom.xml" }}
         - run: mvn dependency:go-offline
         - save_cache: 
            paths:
               - ~/.m2
            key: Spartez-{{ checksum "pom.xml" }}
         - run: mvn package
         - store_test_results: 
            path: target/surefire-reports
         - codecov/upload:
            file: target/my-reports/jacoco.xml
            token: 85b95117-ef42-48ae-941e-1c5e068019c3
         - store_artifacts: 
            path: target/Spartez-0.0.1-SNAPSHOT.jar